export const GET_PROPERTIES_REQUEST = 'GET_PROPERTIES_REQUEST'
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS'
export const GET_PROPERTIES_ERROR = 'GET_PROPERTIES_ERROR'

export const GET_TEMPLATES_REQUEST = 'GET_TEMPLATES_REQUEST'
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS'
export const GET_TEMPLATES_ERROR = 'GET_TEMPLATES_ERROR'
